# The Basics:
NumPy's main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. 

In NumPy dimensions are called axes.

For example, the array for the coordinates of a point in a 3D space, `[1,2,1]`, has one axis. That axis has 3 elements in it, so we say it has a length of 3.

```
[[1., 0., 0.],
[0., 1., 2.]]
```

In the example above, the array has 2 axes.
The first axis has a length of 2, the second axis has a length of 3.

This is because the first axis corresponds to the rows. There are 2 rows, so the first axis has a length of 2.

The second axis corresponds to the columns. Each row has 3 elements, so the second axis has a length of 3

NumPy's array class is called `ndarray`. It is also known by the alias `array`. Note that `numpy.array` is not the same as the Standard Python Library class `array.array`, which only handles one-dimensional arrays and offers less functionality.

The more important attributes of an ndarry object are:
- **ndarray.ndim**
  - The number of axes (dimensions) of the array.
- **ndarry.shape**
  - The dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension.
  - For a matrix with *n* rows and *m* columns, `shape` will be `(n,m)`.
      - The length of the `shape` tuple is therefore the number of axes, `ndim`.
- **ndarray.size**
  - The total number of elements of the array.
  - This is equal to the product of the elements of `shape`.
- **ndarray.dtype**
  - An object describing the type of the elements in the array. One can create or specify dtype's using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.
- **ndarray.itemsize**
  - The size in bytes of each element of the array.
  - For example, an array of elements of type `float64` has `itemsize` 8(=64/8), while one of type `complex32` has `itemsize` 4=(32/8). It is equivalent to `ndarray.dtype.itemsize`.
- **ndarray.data**
  - The buffer containing the actual elements of the array.
  - Normally, we won't need to use this attribute because we will access the elements in an array using indexing facilities.


## An example

In [1]:
import numpy as np

a = np.arange(15).reshape(3, 5)

print(f'Array A:\n{a}\n')

print(f'Array A Shape: {a.shape} \n') # The dimensions of the array. A tuple of integers indicating the size of the array in each dimension.

print(f'Array A Dimensions: {a.ndim} \n')

print(f'Type of the elements in array A: {a.dtype.name} \n')

print(f'The size in bytes of each element in array A (itemsize): {a.itemsize} \n')

print(f'The total number of elements in array A (size): {a.size} \n')

print(f'The type of array A: {type(a)} \n')

b = np.array([6, 7, 8])

print(f'Array B:\n{b}\n')

print(f'The type of array B: {type(b)}')



Array A:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Array A Shape: (3, 5) 

Array A Dimensions: 2 

Type of the elements in array A: int64 

The size in bytes of each element in array A (itemsize): 8 

The total number of elements in array A (size): 15 

The type of array A: <class 'numpy.ndarray'> 

Array B:
[6 7 8]

The type of array B: <class 'numpy.ndarray'>


## Array creation

There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the `array` function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [2]:
import numpy as np
a = np.array([2,3,4])

print(f'Array A:\n{a}\n')

print(f'Type of the elements in array A: {a.dtype} \n')

b = np.array([1.2, 3.5, 5.1])

print(f'Array B:\n{b}\n')

print(f'Type of the elements in array B: {b.dtype} \n')

Array A:
[2 3 4]

Type of the elements in array A: int64 

Array B:
[1.2 3.5 5.1]

Type of the elements in array B: float64 

